/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DebtsRouteImport } from './routes/debts'
import { Route as IndexRouteImport } from './routes/index'

const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsRoute = DebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debts': typeof DebtsRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debts': typeof DebtsRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debts': typeof DebtsRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/debts' | '/expenses' | '/income'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/debts' | '/expenses' | '/income'
  id: '__root__' | '/' | '/debts' | '/expenses' | '/income'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebtsRoute: typeof DebtsRoute
  ExpensesRoute: typeof ExpensesRoute
  IncomeRoute: typeof IncomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebtsRoute: DebtsRoute,
  ExpensesRoute: ExpensesRoute,
  IncomeRoute: IncomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
